import React, { useCallback, useEffect, useState } from "react";
import { useAuthenticatedFetch } from "../../Api/Axios";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Questionlist from "./questions";
import FilterData from "./filterData";

const GeneratePaper = () => {
  const [boards, setBoards] = useState([]);
  const [standards, setStandards] = useState([]);
  const [subjects, setSubjects] = useState([]);
  const [chapters, setChapters] = useState([]);
  const [allData, setAllData] = useState([]);
  const [currentStep, setCurrentStep] = useState(1);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const fetch = useAuthenticatedFetch();

  const [formData, setFormData] = useState({
    board: "",
    standard: "",
    subject: "",
    chapter: "",
    generateType: "",
  });

  const [headerData, setHeaderData] = useState({
    title: "Create Paper",
    subtitle: "Generated By Create Paper",
  });

  const fetchData = useCallback(async () => {
    try {
      const [{ data: boardRes }, { data: allDataRes }] = await Promise.all([
        fetch.get("getBoardData"),
        fetch.get("getAllData"),
      ]);
      setBoards(boardRes.map(({ name }) => ({ label: name, value: name })));
      setAllData(allDataRes);
    } catch (error) {
      toast.error("Failed to fetch initial data.");
    }
  }, [fetch]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleBack = () => {
    if (currentStep > 1) {
      setCurrentStep((prev) => prev - 1);
    }
  };

  const handleNextFromStep1 = () => {
    if (!formData.chapter) {
      toast.error("Please select a chapter.");
      return;
    }
    setCurrentStep(2);
  };

  const handleNextFromStep2 = (e) => {
    e.preventDefault();
    if (!headerData.title.trim() || !headerData.subtitle.trim()) {
      toast.error("Please fill in both Title and Subtitle.");
      return;
    }
    setIsSubmitted(true);
    setCurrentStep(3);
  };

  const updateHeader = useCallback((e) => {
    const { name, value } = e.target;
    setHeaderData((prev) => ({ ...prev, [name]: value }));
  }, []);

  const updateForm = useCallback(
    (e) => {
      const { name, value } = e.target;
      setFormData((prev) => ({ ...prev, [name]: value }));

      switch (name) {
        case "board":
          const selectedBoard = allData.find((b) => b.name === value);
          setStandards(
            selectedBoard?.standards?.map(({ name, _id }) => ({
              label: name,
              value: _id,
            })) || []
          );
          setSubjects([]);
          setChapters([]);
          setFormData((prev) => ({
            ...prev,
            standard: "",
            subject: "",
            chapter: "",
          }));
          break;
        case "standard":
          const currentBoard = allData.find((b) => b.name === formData.board);
          setSubjects(
            currentBoard?.subjects
              ?.filter((sub) => sub.Standard_id === value)
              .map(({ name, _id }) => ({ label: name, value: _id })) || []
          );
          setChapters([]);
          setFormData((prev) => ({ ...prev, subject: "", chapter: "" }));
          break;
        case "subject":
          const currentBoardData = allData.find(
            (b) => b.name === formData.board
          );
          setChapters(
            currentBoardData?.chapters
              ?.filter((ch) => ch.Subject_id === value)
              .map(({ name, _id }) => ({ label: name, value: _id })) || []
          );
          setFormData((prev) => ({ ...prev, chapter: "" }));
          break;
        default:
          break;
      }
    },
    [allData, formData.board]
  );

  const steps = [
    { id: 1, name: "Select Options" },
    { id: 2, name: "Paper Header" },
    { id: 3, name: "Question List" },
  ];

  const renderStepIndicator = useCallback(
    (step) => (
      <div key={step.id} className="step-item">
        <div className="step-details">
          <div
            className={`step-circle ${
              currentStep === step.id
                ? "active"
                : currentStep > step.id
                ? "completed"
                : "inactive"
            }`}
          >
            {currentStep > step.id ? (
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M5 13l4 4L19 7"
                />
              </svg>
            ) : (
              step.id
            )}
          </div>
          <span className="step-name">{step.name}</span>
        </div>
        {step.id < steps.length && (
          <div
            className={`step-separator ${
              currentStep > step.id ? "completed" : "inactive"
            }`}
          ></div>
        )}
      </div>
    ),
    [currentStep, steps.length]
  );

  const renderStep1 = () => (
    <FilterData
      boards={boards}
      standards={standards}
      subjects={subjects}
      chapters={chapters}
      formData={formData}
      updateForm={updateForm}
      goToStep2={handleNextFromStep1}
    />
  );

  const renderStep2 = () => (
    <div className="signin-box">
      <h3 className="paper-header-title">Paper Header Settings</h3>
      <p className="paper-header-subtitle">
        Configure details for the exam paper
      </p>

      <form onSubmit={handleNextFromStep2}>
        <div className="row">
          <div className="form-group">
            <label htmlFor="title">Title</label>
            <input
              type="text"
              name="title"
              className="form-control"
              id="title"
              value={headerData.title}
              onChange={updateHeader}
              placeholder="Enter paper title"
            />
          </div>
          <div className="form-group">
            <label htmlFor="subtitle">Subtitle</label>
            <input
              type="text"
              name="subtitle"
              className="form-control"
              id="subtitle"
              value={headerData.subtitle}
              onChange={updateHeader}
              placeholder="Enter subtitle"
            />
          </div>
        </div>

        <div className="button-container">
          <button
            type="button"
            onClick={handleBack}
            className="button-back-gray"
          >
            Back
          </button>
          <button
            type="submit"
            disabled={!headerData.title.trim() || !headerData.subtitle.trim()}
            className={` ${
              !headerData.title.trim() || !headerData.subtitle.trim()
                ? "button-disabled"
                : "button-next-blue"
            }`}
          >
            Next
          </button>
        </div>
      </form>
    </div>
  );

  const renderStep3 = () => (
    <div className="question-list-wrapper">
      <div className="w-full flex justify-between mb-4">
        <button onClick={handleBack} className="button-back-gray">
          Back
        </button>
        {/* If you have a "Next" or other button for the final step, it will be on the right */}
      </div>
      {formData.chapter ? (
        <Questionlist
          chapterId={formData.chapter}
          formData={formData}
          allData={allData}
          headerData={headerData}
        />
      ) : (
        <div className="error-message">
          No chapter selected. Please go back to Step 1 and select a chapter.
        </div>
      )}
    </div>
  );
  return (
    <div className="content-page">
      <div className="main-content">
        <div className="step-indicator-container">
          {steps.map(renderStepIndicator)}
        </div>

        {currentStep === 1 && renderStep1()}
        {currentStep === 2 &&
          formData.generateType === "Manually" &&
          renderStep2()}
        {currentStep === 3 && isSubmitted && renderStep3()}
        {currentStep === 3 && !isSubmitted && (
          <div className="error-message">
            Error: isSubmitted is false while currentStep is 3.
          </div>
        )}

        <ToastContainer />
      </div>
    </div>
  );
};

export default GeneratePaper;
