import React from "react";
import pdfMake from "../Utils/pdfMakeWrapper";

const GeneratePDF = ({ formData }) => {
  const handleDownload = () => {
    const docDefinition = {

      
      content: [
        {
          columns: [
            {
              text: '', // Placeholder for potential left-side content (like a logo)
              width: 'auto'
            },
            {
              stack: [
                { text: 'Exam Paper', style: 'website', alignment: 'center' },
                { text: 'Paper generated by CreatePaper', style: 'generatedBy', alignment: 'center' }
              ],
              width: '*'
            },
            {
              text: '', // Placeholder for potential right-side content
              width: 'auto'
            }
          ],
          margin: [0, 0, 0, 5]
        },
        {
          table: {
            widths: ['auto', '*', 'auto', '*'],
            body: [
              [
                { text: 'Student Name :', style: 'label' },
                { text: formData.studentName || '_________________', style: 'value' },
                { text: 'Roll No. :', style: 'label' },
                { text: formData.rollNo || '_________________', style: 'value' },
              ],
              [
                { text: `Std : ${formData.std || '_________________'}`, style: 'label' },
                { text: `Date : ${formData.date || '_________________'}`, style: 'value' },
                { text: 'Total Marks :', style: 'label' },
                { text: formData.totalMarks || '_________________', style: 'value' },
              ],
              [
                { text: `Subject : ${formData.sub || '_________________'}`, style: 'label' },
                '', // Empty cell for spacing
                { text: 'Obtain Marks :', style: 'label' },
                { text: formData.obtainMarks || '_________________', style: 'value' },
              ]
            ]
          },
          layout: 'noBorders' // Remove default table borders
        },
        {
          canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: '#000' }],
          margin: [0, 10, 0, 10]
        },
        {
          text: "Instructions:",
          style: "subheader",
          margin: [0, 0, 0, 5]
        },
        {
          ul: [
            "Read all questions carefully.",
            "Answer all questions in the given space.",
            "No electronic gadgets allowed."
          ],
          style: "instructions"
        }
      ],
      styles: {
        website: {
          fontSize: 14,
          bold: true
        },
        generatedBy: {
          fontSize: 10
        },
        label: {
          fontSize: 11,
          bold: true,
          margin: [0, 2, 5, 2] // Add some right margin for spacing
        },
        value: {
          fontSize: 11,
          margin: [0, 2, 0, 2]
        },
        subheader: {
          fontSize: 13,
          bold: true,
          decoration: 'underline',
          margin: [0, 10, 0, 5]
        },
        instructions: {
          fontSize: 10,
          margin: [0, 0, 0, 8]
        }
      },
      pageMargins: [40, 20, 40, 40] // Adjust page margins if needed
    };

    pdfMake.createPdf(docDefinition).download("generate-paper.pdf");
  };

  return <button onClick={handleDownload}>Download PDF</button>;
};

export default GeneratePDF;